### ISSUE TITLE
Add logo/graphic for repository

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/fliscopt#11]
A repository logo/graphic is required for aesthetic purposes.

**Comment by Anik-Bardhan** [comment]
What logo are you planning to give?

**Comment by Agrover112** [comment]
I can attatch few links for reference?

**Comment by Anik-Bardhan** [comment]
@Agrover112 yes alright. And can I be assigned to this then?

**Comment by Agrover112** [comment]
@Anik-Bardhan  refer this: 
https://github.com/Agrover112/awesome-semantic-search
https://github.com/CharlesAverill/satyrn

**Comment by Agrover112** [comment]
@Anik-Bardhan For any questions related to what type of graphic use this discussions tab

**Comment by Anik-Bardhan** [comment]
@Agrover112 just a small query as it is my first time participating in hacktoberfest. Will this be considered as a valid submission or do I have to do something more for this PR?

**Comment by Agrover112** [comment]
> @Agrover112 just a small query as it is my first time participating in hacktoberfest. Will this be considered as a valid submission or do I have to do something more for this PR?

Ok, according to the rules only PRs merged or with label Hacktoberfest-accepted be considered . In general, it should be a valid PR, something that adds value. Any nonsense, useless PRs which don't add value can be marked as invalid/spam hy repo maintainers and that won't be considered.
