### ISSUE TITLE
Add issue and pr templates to the repository.

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/fliscopt#17]

**Comment by kkhitesh** [comment]
Hey, Can I work on this?

**Comment by Agrover112** [comment]
> Hey, Can I work on this?
> 

Sure assigning you.

**Comment by krishguptadev** [comment]
Can I work on the issue?

**Comment by Agrover112** [comment]
> Can I work on the issue?

Maybe work on other issues/ improving README/CONTRIBUTING.md? See if you can improve redundancy?
