### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/fliscopt#19]
- README is not well written and can be improved and structured properly.
- FInding spellling errors.
- Adding emojis.
- Linking missing issues,project tables, referred in README.md.
- Any other improvements to README!

(Quality of your PR matters if it's a non-genuine PR it can be marked as invalid/spam)

**Comment by qwe123coder** [comment]
> * README is not well written and can be improved and structured properly.
> * FInding spellling errors.
> * Adding emojis.
> * Linking missing issues,project tables, referred in README.md.
> * Any other improvements to README!
> 
> (Quality of your PR matters if it's a non-genuine PR it can be marked as invalid/spam)

hey I fixed a few spellings and your read me is good I do not thing you need to add more to it
