### ISSUE TITLE
Add message for failed unittests.

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/fliscopt#35]
A message indicating a failure for each unit-test, should give the user a small idea of what went wrong in the test.
ex: 
`self.assertEqual ( f(values), 0, msg ='HEURISTIC MESSAGE INDICATING WHY TEST CASE FAILED') `

**Comment by Yoda-Canada** [comment]
can I work on this issue?

**Comment by Agrover112** [comment]
> can I work on this issue?

Sure !

**Comment by Agrover112** [comment]
@Yoda-Canada  It's in the README.md in getting started! as **link**

**Comment by Agrover112** [comment]
@Yoda-Canada  So I messed up a bit since I was sleepy. Pls follow me instructions carefully

1.  Delete the **Update fork** I made to your repo. (#3)
2. Accept the Pull Request I made to your fork. (#2)

**Comment by Agrover112** [comment]
@Yoda-Canada  So I raised a PR to YOUR fork.  Accept that PR and make further changes.
Also do this asap, since I do not want your fork to fall behind the master branch again :(
Also maybe if interested at a later date you could check out #42  (similar but might take up huge amount of time on hold for rn)

**Comment by Agrover112** [comment]
> > @Yoda-Canada So I raised a PR to YOUR fork. Accept that PR and make further changes. Also do this asap, since I do not want your fork to fall behind the master branch again :( Also maybe if interested at a later date you could check out #42 (similar but might take up huge amount of time on hold for rn)
> 
> @Agrover112 no worry I will do it ASAP.

I'm awake for your bro :)
