### ISSUE TITLE
Add issue templates.

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/fliscopt#36]
Current Issue Template is a but too verbose. 
Something short simple and sweet that explains the problem would do :)

**Comment by lucianomlima** [comment]
@Agrover112 what you means is that should have less steps or have a more clean layout?

**Comment by Agrover112** [comment]
> @Agrover112 what you means is that should have less steps or have a more clean layout?

A better simpler format, beside bug

**Comment by Agrover112** [comment]
> So you want a new issues template, which covers general issues (not bugs) right?  Can I work on it?

Yup, I think you get it @ShubhayuB
