### ISSUE TITLE
Add an Pull Request template

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/fliscopt#39]
### 👎 Actual Behavior

A template for raising a Pullreq.

### 👍 Expected behavior

same as above

### ✍️ Suggestions to rectify this issue

Create a .yml template for creating a PR template.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Agrover112** [comment]
Sure. Make sure to checkout the already exisiting PR.md , couls you convert that into . yml file?

**Comment by Agrover112** [comment]
@LittleBigProgramming  Status?

**Comment by LittleBigProgramming** [comment]
Couldn't seem to get the current `PULL_REQUEST.md` working but converting it to `pull_request_template.md` did. The content of the file has been left the same. 😄
